name: ceiling_crm
description: Мобильное приложение для управления КП по натяжным потолкам
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.3.3+1
  path: ^1.8.3
  intl: ^0.19.0
  provider: ^6.1.5+1
  share_plus: ^7.2.2
  printing: ^5.14.2
  pdf: ^3.10.6
  path_provider: ^2.1.3
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/standard_positions.json
