name: ceiling_crm
description: CRM для натяжных потолков
publish_to: 'none' # локальный проект

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^9.1.1
  go_router: ^7.2.2
  sqflite: ^2.2.8
  path_provider: ^2.0.16
  image_picker: ^1.0.8
  excel: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Подключаем все папки ассетов
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # Подключаем шрифты
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
