name: ceiling_crm
description: Offline cross-platform CRM for stretch ceilings
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^8.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.14
  intl: ^0.18.1
  image_picker: ^1.1.0
  pdf: ^3.11.0
  excel: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
