name: ceiling_crm
description: A mobile CRM for managing ceiling quotes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  provider: ^6.1.5+1
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^7.2.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  open_file: ^3.3.1  # ДОБАВЛЯЕМ ЭТОТ ПАКЕТ!
  intl: ^0.19.0
  uuid: ^4.5.2
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

 # assets:
   # - assets/
   # - fonts/

 # fonts:
   # - family: Roboto
     # fonts:
       # - asset: fonts/Roboto-Regular.ttf
       # - asset: fonts/Roboto-Bold.ttf
          weight: 700
